### ISSUE TITLE
헐 이게 뭐에욬ㅋㅋㅋㅋㅋ

### ISSUE THREAD

**Issue by 20chan** [RanolP/Capjit#1]
제가 만든 프로그램이 왴ㅋㅋㅋ 이렇게 된거죠 ㅋㅋㅋㅋㅋㅋ 영광입니다

**Comment by RanolP** [comment]
엌 보셨군요, 비스무리하게 만들어보았습니다 (?) 캡짓 잘 쓰고 있어요!

**Comment by 20chan** [comment]
헐...감사합니다..ㅠ
